### ISSUE TITLE
大佬 现在一个域名只能更新一条ip   可以支持多个 么 

### ISSUE THREAD

**Issue by smjcxf1** [frankiejun/cvwt#1]
大佬 现在一个域名只能更新一条ip   可以支持多个 么 
像lee大佬这样的 一个二级域名可以解析多个Ip
https://github.com/lee1080/CloudflareSpeedTestDDNS

**Comment by frankiejun** [comment]
这个实现很简单，只是我测试过多IP用起来效果没有明显变好，反而有点卡，所以没这么做。

**Comment by smjcxf1** [comment]
大佬就是大佬  我小白不懂代码      我让gpt给我写了一个  现在可以实现了   我在服务器运行不卡  我同时跟新6个二级域名也不卡  每个二级域名 5个ip
