### ISSUE TITLE
error start.sh 

### ISSUE THREAD

**Issue by yyqyu** [frankiejun/cvwt#12]
sh start.sh config.yaml 
configfile:config.yaml, ipfile:
start.sh: line 15: //for: not found
0.读取配置文件
start.sh: line 51: syntax error: unexpected redirection

**Comment by frankiejun** [comment]
把 start.sh:  第15行 的 // 改成 #

**Comment by frankiejun** [comment]
你这个运行命令sh start.sh config.yaml， 改为  bash start.sh config.yaml, 或者， chmod +x ./start.sh &&  ./start.sh config.yaml

**Comment by yyqyu** [comment]
我的op可能是有精简，所以bash和./ 都运行不了
改了脚本和权限还是报错了sh start.sh config.yaml
configfile:config.yaml, ipfile:
0.读取配置文件
start.sh: line 51: syntax error: unexpected redirection

**Comment by frankiejun** [comment]
> 我的op可能是有精简，所以bash和./ 都运行不了
> 改了脚本和权限还是报错了sh start.sh config.yaml
> configfile:config.yaml, ipfile:
> 0.读取配置文件
> start.sh: line 51: syntax error: unexpected redirection

因为脚本语法是bash，需要你安装bash。如果没有，就跑不了。
