### ISSUE TITLE
大佬 informlog过大

### ISSUE THREAD

**Issue by smjcxf1** [frankiejun/cvwt#2]
大佬  informlog文件再测国家的时候如果没有测出对于的国家ip   最后在ddns的时候会一直给informlog写入内容
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv
csvfile:TW.csv

**Comment by smjcxf1** [comment]
这个不停一直写入

**Comment by frankiejun** [comment]
能不能把你的配置文件的内容贴出来，我好做复现。记得把api key等私隐信息删掉再发。

**Comment by smjcxf1** [comment]
##cloudflare配置
#cloudflare账号邮箱
x_email: 
 
#域名(多个用逗号分隔)
hostname: 
 jp.a.cc,hk.a.cc,us.a.cc,kr.a.cc,sg.a.cc,tw.a.cc
#空间ID
zone_id: 
 
#Global API Key
api_key: 
 

##openwrt科学上网插件配置
#优选节点时是否自动停止科学上网服务 true: 自动停止 false: 不停止 默认为 true
pause: 
 false
#填写openwrt使用的是哪个科学上网客户端，填写对应的“数字”  默认为 1  客户端为passwall
# 1: passwall 2: passwall2 3: ShadowSocksR Plus+ 4: clash 5: openclash 6: bypass
clien: 
 1
#同一域名更新的ip数量(如果设置值大于实际搜出的ip数量，以实际ip数量为准)
multip: 
 5
#测速地址  
CFST_URL: 
 https://cesu.fkj.pp.ua/50m
#测速线程数量；越多测速越快，性能弱的设备 (如路由器) 请勿太高；(默认 200 最多 1000 )
CFST_N: 200
#延迟测速次数；单个 IP 延迟测速次数，为 1 时将过滤丢包的IP，TCP协议；(默认 4 次 )
CFST_T: 1
#下载测速数量；延迟测速并排序后，从最低延迟起下载测速的数量；(默认 10 个)
CFST_DN: 10
#平均延迟上限；只输出低于指定平均延迟的 IP，可与其他上限/下限搭配；(默认9999 ms 这里推荐配置250 ms)
CFST_TL: 200
#平均延迟下限；只输出高于指定平均延迟的 IP，可与其他上限/下限搭配、过滤假墙 IP；(默认 0 ms 这里推荐配置40)
CFST_TLL:  40
#下载速度下限；只输出高于指定下载速度的 IP，凑够指定数量 [-dn] 才会停止测速；(默认 0.00 MB/s 这里推荐5.00MB/s)
CFST_SL: 10
#是否按国家代码做分组筛选(是: true,否: false)
CCFLAG: true
#需要指定的国家代码,多个用逗号分隔(eg. US,JP)
CCODE: 
 JP,HK,US,KR,SG,TW
#CF服务器对应端口
CF_ADDR: 443
##TG推送设置
#（填写即为开启推送，未填写则为不开启）
#TG机器人token 例如：123456789: ABCDEFG...
export telegramBotToken= 
 
export telegramBotUserId=

**Comment by smjcxf1** [comment]
配置就按 你写的填的

**Comment by smjcxf1** [comment]
大佬 你有tg群么 我去你群

**Comment by frankiejun** [comment]
感谢，你发现了一个大bug。另外建议你设置 CFST_SL: 5 ，multip 设置3 就好，不是越大越好的。 bug已修复，下载最新版试试吧。 另外，我没tg群。

**Comment by dust2k** [comment]
> 感谢，你发现了一个大bug。另外建议你设置 CFST_SL: 5 ，multip 设置3 就好，不是越大越好的。 bug已修复，下载最新版试试吧。 另外，我没tg群。

开一个TG群啊，用这个issue找你解决问题，要如果需要讨论的话，太慢了。。
