### ISSUE TITLE
连接Cloudflare的网站总是失败

### ISSUE THREAD

**Issue by dust2k** [frankiejun/cvwt#3]
用 start.sh 脚本跑，每次都是认证失败，但偶尔可以成功，所以是不是把那个URL调用认证的timeout能设的时间长点。。这边成功率稍微高点。。

还有就是跑成功了，优选出IP之后，更新Cloudflare的DNS记录总是失败，从来没一次成功的，我看你现在好像是用删除再加入的方法，貌似不怎么好用啊。。也可能你那边好用，我这里上cloudflare的速度太慢导致失败的？

**Comment by dust2k** [comment]
应该是我这边的网络给封了，我改了全局之后就都跑通了，唉。。

**Comment by frankiejun** [comment]
应该是download ip文件的时候卡了吧，那里需要翻墙才能下载。 你在openwert（作为旁路由）中运行，本来就能翻墙，脚本中会启停你的翻墙软件，例如passwall。 中间出问题有概率会不能复启你的代理，如果一直卡在下载那里，或者你试过不能翻墙，就是代理被关了。可以手动启动，以passwall为例， 执行:   /etc/init.d/passwall start
