### ISSUE TITLE
是否支持arm 的R4S 软路由

### ISSUE THREAD

**Issue by tiancool** [frankiejun/cvwt#5]
cf_ddns: line 239: ./CloudflareST: cannot execute binary file: Exec format error

提示错误，下载原版的 CloudflareST 可以使用，能否修改支持arm 的 R4S 软路由 openWRT，感谢

**Comment by dust2k** [comment]
CloudflareST肯定是X86的binary啊。。应该在cloudflarest的repo里能找到arm的binary吧。。

**Comment by tiancool** [comment]
> CloudflareST肯定是X86的binary啊。。应该在cloudflarest的repo里能找到arm的binary吧。。

是的，我试过直接替换无法使用作者的这个项目呢

**Comment by shyyhs19625** [comment]
> > CloudflareST肯定是X86的binary啊。。应该在cloudflarest的repo里能找到arm的binary吧。。
> 
> 是的，我试过直接替换无法使用作者的这个项目呢

替换了2.2.5的arm64的,可以使用

**Comment by tiancool** [comment]
换了也不行，帮忙看下什么问题
`2.Select the ip address of the desired port.
handling: ./31898-1-443.txt
handling: ./45102-1-443.txt
Run scripts to test speed and update dns records.
Cloudflare账号验证成功
当前工作模式为ipv4
按要求未停止科学上网服务
./CloudflareST -url https://cesu.fkj.pp.ua/20m -t 1 -n 200 -dn 10 -tl 250 -tll 40 -sl 5 -p 10    -tp 443 -c  -cc HK,TW,SG,US,JP,KR 
flag provided but not defined: -c

CloudflareSpeedTest v2.2.5
测试 Cloudflare CDN 所有 IP 的延迟和速度，获取最快 IP (IPv4+IPv6)！
https://github.com/XIU2/CloudflareSpeedTest

参数：
    -n 200
        延迟测速线程；越多延迟测速越快，性能弱的设备 (如路由器) 请勿太高；(默认 200 最多 1000)
    -t 4
        延迟测速次数；单个 IP 延迟测速的次数；(默认 4 次)
    -dn 10
        下载测速数量；延迟测速并排序后，从最低延迟起下载测速的数量；(默认 10 个)
    -dt 10
        下载测速时间；单个 IP 下载测速最长时间，不能太短；(默认 10 秒)
    -tp 443
        指定测速端口；延迟测速/下载测速时使用的端口；(默认 443 端口)
    -url https://cf.xiu2.xyz/url
        指定测速地址；延迟测速(HTTPing)/下载测速时使用的地址，默认地址不保证可用性，建议自建；

    -httping
        切换测速模式；延迟测速模式改为 HTTP 协议，所用测试地址为 [-url] 参数；(默认 TCPing)
    -httping-code 200
        有效状态代码；HTTPing 延迟测速时网页返回的有效 HTTP 状态码，仅限一个；(默认 200 301 302)
    -cfcolo HKG,KHH,NRT,LAX,SEA,SJC,FRA,MAD
        匹配指定地区；地区名为当地机场三字码，英文逗号分隔，仅 HTTPing 模式可用；(默认 所有地区)

    -tl 200
        平均延迟上限；只输出低于指定平均延迟的 IP，各上下限条件可搭配使用；(默认 9999 ms)
    -tll 40
        平均延迟下限；只输出高于指定平均延迟的 IP；(默认 0 ms)
    -tlr 0.2
        丢包几率上限；只输出低于/等于指定丢包率的 IP，范围 0.00~1.00，0 过滤掉任何丢包的 IP；(默认 1.00)
    -sl 5
        下载速度下限；只输出高于指定下载速度的 IP，凑够指定数量 [-dn] 才会停止测速；(默认 0.00 MB/s)

    -p 10
        显示结果数量；测速后直接显示指定数量的结果，为 0 时不显示结果直接退出；(默认 10 个)
    -f ip.txt
        IP段数据文件；如路径含有空格请加上引号；支持其他 CDN IP段；(默认 ip.txt)
    -ip 1.1.1.1,2.2.2.2/24,2606:4700::/32
        指定IP段数据；直接通过参数指定要测速的 IP 段数据，英文逗号分隔；(默认 空)
    -o result.csv
        写入结果文件；如路径含有空格请加上引号；值为空时不写入文件 [-o ""]；(默认 result.csv)

    -dd
        禁用下载测速；禁用后测速结果会按延迟排序 (默认按下载速度排序)；(默认 启用)
    -allip
        测速全部的IP；对 IP 段中的每个 IP (仅支持 IPv4) 进行测速；(默认 每个 /24 段随机测速一个 IP)

    -v
        打印程序版本 + 检查版本更新
    -h
        打印帮助说明
测速完毕
按要求未重启科学上网服务
正在更新域名，请稍后...
csvfile:HK.csv csvfile:TW.csv csvfile:SG.csv csvfile:US.csv csvfile:JP.csv csvfile:KR.csv
未配置TG推送
Restore background process.
nohup: ignoring input and redirecting stderr to stdout
nohup: appending output to 'nohup.out'`

**Comment by frankiejun** [comment]
原版肯定没有这个按国家地区筛选的功能，这是我加上去的。你的是arm64吗？ 

> 换了也不行，帮忙看下什么问题 `2.Select the ip address of the desired port. handling: ./31898-1-443.txt handling: ./45102-1-443.txt Run scripts to test speed and update dns records. Cloudflare账号验证成功 当前工作模式为ipv4 按要求未停止科学上网服务 ./CloudflareST -url https://cesu.fkj.pp.ua/20m -t 1 -n 200 -dn 10 -tl 250 -tll 40 -sl 5 -p 10 -tp 443 -c -cc HK,TW,SG,US,JP,KR flag provided but not defined: -c
> 
> CloudflareSpeedTest v2.2.5 测试 Cloudflare CDN 所有 IP 的延迟和速度，获取最快 IP (IPv4+IPv6)！ https://github.com/XIU2/CloudflareSpeedTest
> 
> 参数： -n 200 延迟测速线程；越多延迟测速越快，性能弱的设备 (如路由器) 请勿太高；(默认 200 最多 1000) -t 4 延迟测速次数；单个 IP 延迟测速的次数；(默认 4 次) -dn 10 下载测速数量；延迟测速并排序后，从最低延迟起下载测速的数量；(默认 10 个) -dt 10 下载测速时间；单个 IP 下载测速最长时间，不能太短；(默认 10 秒) -tp 443 指定测速端口；延迟测速/下载测速时使用的端口；(默认 443 端口) -url https://cf.xiu2.xyz/url 指定测速地址；延迟测速(HTTPing)/下载测速时使用的地址，默认地址不保证可用性，建议自建；
> 
> ```
> -httping
>     切换测速模式；延迟测速模式改为 HTTP 协议，所用测试地址为 [-url] 参数；(默认 TCPing)
> -httping-code 200
>     有效状态代码；HTTPing 延迟测速时网页返回的有效 HTTP 状态码，仅限一个；(默认 200 301 302)
> -cfcolo HKG,KHH,NRT,LAX,SEA,SJC,FRA,MAD
>     匹配指定地区；地区名为当地机场三字码，英文逗号分隔，仅 HTTPing 模式可用；(默认 所有地区)
> 
> -tl 200
>     平均延迟上限；只输出低于指定平均延迟的 IP，各上下限条件可搭配使用；(默认 9999 ms)
> -tll 40
>     平均延迟下限；只输出高于指定平均延迟的 IP；(默认 0 ms)
> -tlr 0.2
>     丢包几率上限；只输出低于/等于指定丢包率的 IP，范围 0.00~1.00，0 过滤掉任何丢包的 IP；(默认 1.00)
> -sl 5
>     下载速度下限；只输出高于指定下载速度的 IP，凑够指定数量 [-dn] 才会停止测速；(默认 0.00 MB/s)
> 
> -p 10
>     显示结果数量；测速后直接显示指定数量的结果，为 0 时不显示结果直接退出；(默认 10 个)
> -f ip.txt
>     IP段数据文件；如路径含有空格请加上引号；支持其他 CDN IP段；(默认 ip.txt)
> -ip 1.1.1.1,2.2.2.2/24,2606:4700::/32
>     指定IP段数据；直接通过参数指定要测速的 IP 段数据，英文逗号分隔；(默认 空)
> -o result.csv
>     写入结果文件；如路径含有空格请加上引号；值为空时不写入文件 [-o ""]；(默认 result.csv)
> 
> -dd
>     禁用下载测速；禁用后测速结果会按延迟排序 (默认按下载速度排序)；(默认 启用)
> -allip
>     测速全部的IP；对 IP 段中的每个 IP (仅支持 IPv4) 进行测速；(默认 每个 /24 段随机测速一个 IP)
> 
> -v
>     打印程序版本 + 检查版本更新
> -h
>     打印帮助说明
> ```
> 
> 测速完毕 按要求未重启科学上网服务 正在更新域名，请稍后... csvfile:HK.csv csvfile:TW.csv csvfile:SG.csv csvfile:US.csv csvfile:JP.csv csvfile:KR.csv 未配置TG推送 Restore background process. nohup: ignoring input and redirecting stderr to stdout nohup: appending output to 'nohup.out'`

**Comment by thathooo** [comment]
> 原版肯定没有这个按国家地区筛选的功能，这是我加上去的。你的是arm64吗？
> 
设备信息： Phicomm N1
CPU 型号:  AArch64 : Cortex-A53 x 4
错误信息：`-bash: ./CloudflareST: cannot execute binary file: Exec format error`

似乎是同样的问题，希望能编译一个arm架构的CloudflareST

**Comment by smjcxf** [comment]
> > 原版肯定没有这个按国家地区筛选的功能，这是我加上去的。你的是arm64吗？
> 
> 设备信息： Phicomm N1 CPU 型号: AArch64 : Cortex-A53 x 4 错误信息：`-bash: ./CloudflareST: cannot execute binary file: Exec format error`
> 
> 似乎是同样的问题，希望能编译一个arm架构的CloudflareST

arm64的
[Uploading CloudflareST.zip…]()
你用这个试试

**Comment by smjcxf** [comment]
[CloudflareST.zip](https://github.com/frankiejun/cvwt/files/15285274/CloudflareST.zip)

**Comment by thathooo** [comment]
谢谢，在我的arm路由生效了，麻烦您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frankiejun/cvwt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月12日(星期天) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frankiejun/cvwt] 是否支持arm 的R4S 软路由 (Issue #5)





   
原版肯定没有这个按国家地区筛选的功能，这是我加上去的。你的是arm64吗？
  
设备信息： Phicomm N1 CPU 型号: AArch64 : Cortex-A53 x 4 错误信息：-bash: ./CloudflareST: cannot execute binary file: Exec format error
 
似乎是同样的问题，希望能编译一个arm架构的CloudflareST
  
arm64的
 Uploading CloudflareST.zip…
 你用这个试试

**Comment by frankiejun** [comment]
> 谢谢，在我的arm路由生效了，麻烦您了
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "frankiejun/cvwt"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年5月12日(星期天) 下午2:21
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [frankiejun/cvwt] 是否支持arm 的R4S 软路由 (Issue #5)
> 
> 
> 
> 
> 
>    
> 原版肯定没有这个按国家地区筛选的功能，这是我加上去的。你的是arm64吗？
>   
> 设备信息： Phicomm N1 CPU 型号: AArch64 : Cortex-A53 x 4 错误信息：-bash: ./CloudflareST: cannot execute binary file: Exec format error
>  
> 似乎是同样的问题，希望能编译一个arm架构的CloudflareST
>   
> arm64的
>  Uploading CloudflareST.zip…
>  你用这个试试
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

怎么生效的，你自己编译了？

**Comment by thathooo** [comment]
> > 谢谢，在我的arm路由生效了，麻烦您了
> > ------------------ 原始邮件 ------------------
> > 发件人:                                                                                                                        "frankiejun/cvwt"                                                                                    _**@**_._**>;
> > 发送时间: 2024年5月12日(星期天) 下午2:21
> > _**@**_.**_>;
> > _**@**_._**_**@**_.**_>;
> > 主题: Re: [frankiejun/cvwt] 是否支持arm 的R4S 软路由 (Issue #5)
> > 原版肯定没有这个按国家地区筛选的功能，这是我加上去的。你的是arm64吗？
> > 设备信息： Phicomm N1 CPU 型号: AArch64 : Cortex-A53 x 4 错误信息：-bash: ./CloudflareST: cannot execute binary file: Exec format error
> > 似乎是同样的问题，希望能编译一个arm架构的CloudflareST
> > arm64的
> > Uploading CloudflareST.zip…
> > 你用这个试试
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 怎么生效的，你自己编译了？

其实我也有点奇怪，我收到了github的回复邮件，就是我上条回复中quote部分，但没有在这里看到同步的回复，落款为 Smj.Love.C
其中附带了似乎是这个repo的文件地址，我下载尝试可以正常运行，还以为是你回复的，链接在下面：
https://github.com/frankiejun/cvwt/files/15285274/CloudflareST.zip

**Comment by smjcxf1** [comment]
其实你自己编译一个就行很简单

**Comment by smjcxf1** [comment]
回复信息我删了

**Comment by thathooo** [comment]
> 回复信息我删了

原来是这样，十分感谢帮助，其实我昨天在考虑是编译还是放弃，然后忘记了，今天正要尝试编译就收到您的邮件，现在已经正常使用了。

**Comment by frankiejun** [comment]
[CloudflareST_arm64.zip](https://github.com/frankiejun/cvwt/files/15286611/CloudflareST_arm64.zip)

你试试我附件中这个，因为我没有环境，自己试不了。  行不行都回复一下，如果可以我就发布这个。

> > 回复信息我删了
> 
> 原来是这样，十分感谢帮助，其实我昨天在考虑是编译还是放弃，然后忘记了，今天正要尝试编译就收到您的邮件，现在已经正常使用了。

**Comment by thathooo** [comment]
> [CloudflareST_arm64.zip](https://github.com/frankiejun/cvwt/files/15286611/CloudflareST_arm64.zip)
> 
> 你试试我附件中这个，因为我没有环境，自己试不了。 行不行都回复一下，如果可以我就发布这个。
> 

好的，我的运行环境：
设备： Phicomm N1
CPU: AArch64 : Cortex-A53 x 4
固件版本：OpenWrt R24.01.26 (by flippy) / LuCI Master (git-24.019.37088-cdf2b69)
内核版本：5.15.148-flippy-87+o
网络环境：单臂旁路由，OpenClash (FakeIP-TUN), Zerotier

下面是运行输出：

```
root@bypass:~/openwrt# ./start.sh config.yaml
configfile:config.yaml, ipfile:
0.读取配置文件
domain_num:3, countryCode_num:3
1.Download ip file.
--2024-05-12 22:38:17--  https://zip.baipiao.eu.org/
Resolving zip.baipiao.eu.org... 198.18.0.19
Connecting to zip.baipiao.eu.org|198.18.0.19|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: 'txt.zip'

txt.zip                                       [ <=>                                                                               ]  19.84K  --.-KB/s    in 0.08s   

2024-05-12 22:38:18 (253 KB/s) - 'txt.zip' saved [20312]

downloaded.
Archive:  txt.zip
  inflating: 31898-0-2052.txt        
  inflating: 31898-0-2082.txt        
  inflating: 31898-0-2086.txt        
  inflating: 31898-0-2095.txt        
  inflating: 31898-0-80.txt          
  inflating: 31898-0-8080.txt        
  inflating: 31898-0-8880.txt        
  inflating: 31898-1-2053.txt        
  inflating: 31898-1-2083.txt        
  inflating: 31898-1-2087.txt        
  inflating: 31898-1-2096.txt        
  inflating: 31898-1-443.txt         
  inflating: 31898-1-8443.txt        
  inflating: 45102-0-2052.txt        
  inflating: 45102-0-2082.txt        
  inflating: 45102-0-2086.txt        
  inflating: 45102-0-2095.txt        
  inflating: 45102-0-80.txt          
  inflating: 45102-0-8080.txt        
  inflating: 45102-0-8880.txt        
  inflating: 45102-1-2053.txt        
  inflating: 45102-1-2083.txt        
  inflating: 45102-1-2087.txt        
  inflating: 45102-1-2096.txt        
  inflating: 45102-1-443.txt         
  inflating: 45102-1-8443.txt        
2.Select the ip address of the desired port.
handling: ./31898-1-443.txt
handling: ./45102-1-443.txt
Run scripts to test speed and update dns records.
Cloudflare账号验证成功
当前工作模式为ipv4
OpenClash Already Stop!
已停止openclash
./CloudflareST  -t 1 -n 200 -dn 10 -tl 250 -tll 40 -sl 5 -p 10    -tp 443 -c  -cc JP,US,KR 
分国家测速模式
# XIU2/CloudflareSpeedTest  

开始延迟测速（模式：TCP, 端口：443, 范围：40 ~ 250 ms, 丢包：1.00)
212 / 212 [----------------------------------------------------------------------------------------------------------------------------------------------] 可用: 46  
开始查询IP的国家代号...

[信息] 开始测速 JP 的 IP，数量：1
0 / 1 [___________________________________________________________________________________________________________________________________________________]          

[信息] 开始测速 KR 的 IP，数量：6
0 / 6 [___________________________________________________________________________________________________________________________________________________]          

[信息] 开始测速 US 的 IP，数量：15
0 / 10 [_________________________________________________________________________________________________________________________________________________]           
测速完毕
OpenClash Restart...
OpenClash Already Stop!
OpenClash Already Start!
已重启openclash
为保证cloudflareAPI连接正常 将在3秒后开始更新域名解析
正在更新域名，请稍后...
csvfile:JP.csv 开始更新第1个---158.101.71.60 recordIp:168.138.212.87 jp-fd.xxx.xxx更新成功 完成JP.csv的ip更新! csvfile:US.csv 开始更新第1个---131.186.28.236 recordIp:129.146.248.140 us-fd.xxx.xxx更新成功 完成US.csv的ip更新! csvfile:KR.csv 开始更新第1个---146.56.44.88 recordIp:146.56.44.88 更新失败，获取最快的IP与云端相同 kr-fd.xxx.xxx更新失败 完成KR.csv的ip更新!
TG推送失败，请检查TG机器人token和ID
Restore background process.
nohup: ignoring input and redirecting stderr to stdout
nohup: appending output to 'nohup.out'
OpenClash Already Start!

```

**Comment by frankiejun** [comment]
ok，那就是可以用
