### ISSUE TITLE
pause=false时会重复start翻墙软件

### ISSUE THREAD

**Issue by livingfree2023** [frankiejun/cvwt#6]
原代码
```
trap handle_err EXIT
```
且`handle_err`中未判断`pause`值，会重复启动翻墙服务，
建议改为
```
trap handle_err HUP INT TERM
```
并且`handle_err`中加入`if [ "$pause" = "true" ] ; then`的保护

祝好

**Comment by frankiejun** [comment]
嗯，谢谢建议，后面我改一下。

**Comment by livingfree2023** [comment]
不过我觉得 https://github.com/mingxiaoyu/luci-app-cloudflarespeedtest 这个luci的程序，在测速期间，通过`uci set`的方式把passwall运行模式改成gfw模式是个很好的方法，因为有的时候测速时间可能很长（10分钟以上？），强行关掉服务有可能造成不便。

可惜上述这个项目目前不兼容最新的passwall了，但是我读了一下里面核心代码就是通过
```shell
uci set "passwall.@global[0].tcp_proxy_mode"='direct'
uci commit
``` 
来关掉默认转发，然后通过
```shell
uci set "passwall.@global[0].tcp_proxy_mode"='proxy'
uci commit
``` 
来再打开默认转发。
当然也可以把原来的用户设置保存在变量中，结束后恢复即可。

当然这些代码只针对passwall，其他代理需要用其他的变量控制。

祝好
