### ISSUE TITLE
1.0.8版本有个bug

### ISSUE THREAD

**Issue by t65275686** [frankiejun/cvwt#9]
config里设置hostname两个，用逗号隔开的，multip是1，跑完之后两个域名的DNS是一样的
以下部分日志：
开始延迟测速（模式：TCP, 端口：443, 范围：10 ~ 180 ms, 丢包：0.05)
       IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
172.64.160.203    20      20      0.00    134.64    36.61          
172.64.135.218    20      20      0.00    134.61    14.64  

正在更新域名，请稍后...
开始更新第1个---172.64.160.203 新增cf1.**********s.top 的DNS记录 cf1.**********s.top更新成功 完成result.csv的ip更新! 开始更新第1个---172.64.160.203 新增cf2.**********s.top 的DNS记录 cf2.**********s.top更新成功 完成result.csv的ip更新!
开始更新第1个---172.64.160.203 新增cf1.**********s.top 的DNS记录 cf1.**********s.top更新成功 完成result.csv的ip更新! 开始更新第1个---172.64.160.203 新增cf2.**********s.top 的DNS记录 cf2.**********s.top更新成功 完成result.csv的ip更新!
TG推送失败，请检查TG机器人token和ID

**Comment by t65275686** [comment]
换了版本。。还是这样。难道脚本逻辑就是这样的？多个hostname也只更新最快的同一个IP吗？

**Comment by frankiejun** [comment]
multip=1 就是一个域名对应一个ip。 每个ip都是抽文件中第一条。你看过我youtube上的视频吗，可以再仔细看看
